version: '2.1'
services:
  antd-testsys-client:
    image: 'nginx:alpine'
    container_name: 'antd-testsys-client'
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - './dist:/usr/share/nginx/html'
    # command: 'sh -c "npm config set registry https://registry.npm.taobao.org && /bin/sh"'