export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const FETCH_COMMONDATA = 'FETCH_COMMONDATA';
export const FETCH_COMMONDATA_SUCCESS = 'FETCH_COMMONDATA_SUCCESS';
export const FETCH_COMMONDATA_FAILED = 'FETCH_COMMONDATA_FAILED';

export const FETCH_RANKING = 'FETCH_RANKING';
export const FETCH_RANKING_SUCCESS = 'FETCH_RANKING_SUCCESS';
export const FETCH_RANKING_FAILED = 'FETCH_RANKING_FAILED';
